spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: 9010          
